echo deleting temp g1Assemblies.............................
rd /s /q "C:\Users\nex34kv\AppData\Local\Temp\g1Assemblies\"
echo deleting appdata Pitney  Bowes.............................
rd /s /q "<C:\Users\nex34kv\AppData\Roaming\Pitney Bowes\>"